blank_issues_enabled: false
contact_links:
  - name: About this project
    url: https://github.com/sre/gpxcut/blob/main/.github/CONTRIBUTING.md
    about: >
      This is a personal project. External contributions and bug reports are not
      expected. Please read CONTRIBUTING.md before opening an issue.
